# This workflow will install Python dependencies, run the helper with a single version of Python

name: backup-pl
on:
  repository_dispatch:
    types: update-pl

jobs:

  backup-playlist:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install ffmpeg
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: make Backup
      env:
        TITLE: ${{ github.event.client_payload.title }}
      run: |
        python bot.py
        find . -name '*.mp3' -exec echo {} \;
