# This workflow will install Python dependencies, run the helper with a single version of Python

name: Youtube-dl JOB

on:

  schedule:
    #once every 10 minutes
    - cron: "*/5 * * * *"
  push:
    branches: [master]

jobs:

  backup-playlist:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Update the Stats
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      run: |
        python bot.py
        echo "Backup Updated"